server:
  port: 20001
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
  application:
    name: coupon-customer-serv
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        metadata:
          myData: abc
        namespace: dev
        group: myGroup
        register-enabled: true
        naming-load-cache-at-start: false
    openfeign:
      client:
        config:
          coupon-template-feign-client:
            connectTimeout: 1000
            readTimeour: 2000
            loggerLevel: full
          coupon-calculation-feign-client:
            connectTimeout: 2000
            readTimeout: 3000
            loggerLevel: full

  datasource:
    # mysql数据源
    url: jdbc:mysql://127.0.0.1:3306/coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: CloudCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false

logging:
  level:
    top.wml.coupon: debug
    top.wml.coupon.customer.feign.TemplateService: debug
    top.wml.coupon.customer.feign.CalculationService: debug

