server:
  port: 20002
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
  application:
    name: coupon-calculation-serv
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        metadata:
          myData: abc
        namespace: dev
        group: myGroup
        register-enabled: true
        naming-load-cache-at-start: false
logging:
  level:
    top.mqxu.coupon: debug

# 开启所有management端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

